### ISSUE TITLE
Update schema files for OEP-8 version 0.4

### ISSUE THREAD

**Issue by ttmc** [oceanprotocol/plecos#19]
Some changes were made to OEP-8 between version 0.3 and version 0.4. You can get a sense of most of those changes (e.g. adding the "services" array) by looking at https://github.com/oceanprotocol/OEPs/pull/172

The Plecos schema files need to be updated for OEP-8 version 0.4.

**Comment by ttmc** [comment]
Please hold off on resolving this issue until OEP-8 version 0.4 is more final.

**Comment by eruizgar91** [comment]
Implemented
